export enum HttpErrorCode {
  EMAIL_NOT_FOUNT = 1,
  PASSWORD_IS_INVALID = 2,
  INVALID_REQUEST_BODY = 3,
  NOT_AUTHENTICATED = 4,
  UID_NOT_FOUND = 5,
  TWO_FACTOR_SETUP_REQUIRED = 6,
  TWO_FACTOR_NOT_ENABLED = 7,
  INVALID_TWO_FACTOR_CODE = 8,
  TWO_FACTOR_ALREADY_ENABLED = 9
}
