name: Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.WEBSITE_ENV }} > .env
      - name: Build
        run: npm run build
