name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_ACCESS_KEY_ID: "a"
      S3_SECRET_ACCESS_KEY: "a"
      S3_REGION: "eu-west"
      S3_ENDPOINT: "http://127.0.0.1:9000"
      S3_BUCKET_NAME: "instamint"
      DATABASE_URL: "postgresql://instamint:instamint@localhost:5432/instamint"
      GMAIL_EMAIL: "instamint.noreply@gmail.com"
      GMAIL_PASS: "a"
      NEXT_PUBLIC_PUBLISHABLE_KEY: "a"
      PEPPER_PASSWORD_SECRET: "a"
      NEXT_PUBLIC_TEST_DATA: "a"
      NEXT_AUTH_SECRET: "a"
      SECURE_AUTH_COOKIES: "false"
      TOTP_ENCRYPTION_KEY: "a"
      TRUST_HOST: "false"
      BASE_URL: "http://localhost:3000"
      CONTACT_EMAIL: instamint.contact@gmail.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
