name: Continous Integration

on: [push, pull_request]
jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        uses: npm run build

  lint:
    run-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint
        uses: npm run build
