on: [push, pull_request]
jobs:

#TODO add Jest and playwright

#  test:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Install dependencies
#        run: npm install
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#      - name: Run Playwright tests
#        run: npx playwright test
